# Use sudo rights
sudo: required

# Install a copy of Docker cli into the container
services:
  - docker

 # Build image using 'Dockerfile.dev' and tag as marktug/docker-react (will be used instead of container_id)

before_install:
  - docker build -t scowil101/docker-react -f Dockerfile.dev .
 
# Run test suite - Overide default command with 'npm run test'
script:
  - docker run -e CI=true scowil101/docker-react npm run test
   
# Deploy to AWS Elastic Beanstalk
deploy:

  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-485621712162"
  bucket_path: "docker"
  on:
    branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY